// src/org/jenkins/GithubAppAuth.groovy
package org.jenkins

import groovy.json.JsonSlurper

class GithubAppAuth implements Serializable {

  def script
  final String GITHUB_API = 'https://api.github.com'

  // Cached token state
  private String cachedToken     = null
  private long   tokenIssuedAt   = 0
  private static final long TOKEN_TTL = 55 * 60 * 1000  // 55 min in ms (token lasts 1hr, refresh at 55min)

  GithubAppAuth(script) {
    this.script = script
  }

  // ─────────────────────────────────────────────────────────────
  // ENTRY POINT — call this from prPipeline Stage 2
  // credentialsId: Jenkins credential ID of type 'GitHub App'
  // ─────────────────────────────────────────────────────────────
  def verifyAndInject(String credentialsId) {

    script.echo "🔐 Stage 2 — GitHub App verification starting..."

    // Step 1: get the JWT via plugin credential binding
    def jwt = _issueJwt(credentialsId)

    // Step 2: verify app is authenticated at all
    _verifyAppAuth(jwt)

    // Step 3: verify app is actually installed on THIS repo
    _verifyRepoInstallation(jwt)

    // Step 4: generate repo-scoped token
    def repoToken = _createRepoToken(jwt)

    // Cache it with timestamp
    cachedToken   = repoToken
    tokenIssuedAt = System.currentTimeMillis()

    // Step 5: inject into env for downstream stages
    script.env.GITHUB_TOKEN      = repoToken
    script.env.GITHUB_CRED_ID    = credentialsId  // stored so reissueToken knows which cred to use

    script.echo "✅ Stage 2 — GitHub App verified and repo token injected"
  }

  // ─────────────────────────────────────────────────────────────
  // ISSUE TOKEN
  // Uses GitHub Branch Source plugin — it handles JWT signing
  // and installation token exchange natively
  // ─────────────────────────────────────────────────────────────
  private String _issueJwt(String credentialsId) {
    def token = ''

    // usernamePassword is how GitHub Branch Source plugin exposes the App token
    // username = App ID
    // password = short-lived installation token (auto-generated by plugin) or JWT
    script.withCredentials([
      script.usernamePassword(
        credentialsId: credentialsId,
        usernameVariable: 'GH_APP_ID',
        passwordVariable: 'GH_APP_TOKEN'
      )
    ]) {
      token = script.env.GH_APP_TOKEN
    }

    if (!token) {
      script.error("❌ Failed to obtain token from credential '${credentialsId}' — is it a GitHub App credential?")
    }

    script.echo "🔑 App JWT issued"
    return token
  }

  // ─────────────────────────────────────────────────────────────
  // REISSUE TOKEN — call this in long pipelines before token expires
  // Checks age first — only reissues if within 5min of expiry
  // ─────────────────────────────────────────────────────────────
  String reissueToken(String credentialsId = null) {
    def credId = credentialsId ?: script.env.GITHUB_CRED_ID

    if (!credId) {
      script.error("❌ reissueToken: no credentialsId provided and GITHUB_CRED_ID not set in env")
    }

    def age = System.currentTimeMillis() - tokenIssuedAt

    if (cachedToken && age < TOKEN_TTL) {
      def remainingMin = ((TOKEN_TTL - age) / 60000).toInteger()
      script.echo "♻️  Token still valid (~${remainingMin}min remaining) — reuse without reissue"
      return cachedToken
    }

    script.echo "🔄 Token expired or nearing expiry — reissuing..."
    
    // Get fresh JWT
    def jwt = _issueJwt(credId)
    // Generate new repo token
    def newRepoToken = _createRepoToken(jwt)

    // Cache it with timestamp
    cachedToken   = newRepoToken
    tokenIssuedAt = System.currentTimeMillis()

    // Update env so downstream stages get the fresh token automatically
    script.env.GITHUB_TOKEN = newRepoToken

    script.echo "✅ Token reissued and env updated"
    return newRepoToken
  }

  // ─────────────────────────────────────────────────────────────
  // PRIVATE — verify the token works at the app level
  // GET /app → should return 200 with app metadata
  // ─────────────────────────────────────────────────────────────
  private void _verifyAppAuth(String token) {
    script.echo "   Checking GitHub App authentication..."

    def response = script.sh(
      script: """
        curl -s -w "\\n%{http_code}" \\
          -H "Authorization: Bearer ${token}" \\
          -H "Accept: application/vnd.github+json" \\
          ${GITHUB_API}/app
      """,
      returnStdout: true
    ).trim()

    def lines    = response.split('\n')
    def httpCode = lines[-1]
    def body     = lines[0..-2].join('\n')

    if (httpCode != '200') {
      script.error("❌ GitHub App auth check failed — HTTP ${httpCode}\n${body}")
    }

    def json    = new JsonSlurper().parseText(body)
    script.echo "   ✅ App authenticated: '${json.name}' (ID: ${json.id})"
  }

  // ─────────────────────────────────────────────────────────────
  // PRIVATE — verify app is installed on THIS specific repo
  // GET /repos/{owner}/{repo}/installation → 200 = installed, 404 = not installed
  // ─────────────────────────────────────────────────────────────
  private void _verifyRepoInstallation(String token) {
    def repo = script.env.GH_REPO   // set by DefaultEnv in Stage 1 e.g. 'org/repo-name'

    if (!repo) {
      script.error("❌ GH_REPO env var not set — did Stage 1 (DefaultEnv) run?")
    }

    script.echo "   Checking App is installed on repo: ${repo}..."

    def response = script.sh(
      script: """
        curl -s -w "\\n%{http_code}" \\
          -H "Authorization: Bearer ${token}" \\
          -H "Accept: application/vnd.github+json" \\
          ${GITHUB_API}/repos/${repo}/installation
      """,
      returnStdout: true
    ).trim()

    def lines    = response.split('\n')
    def httpCode = lines[-1]
    def body     = lines[0..-2].join('\n')

    switch (httpCode) {
      case '200':
        def json = new JsonSlurper().parseText(body)
        script.echo "   ✅ App installed on '${repo}' (installation ID: ${json.id})"
        // Store installation ID — useful for later API calls
        script.env.GH_APP_INSTALLATION_ID = json.id.toString()
        break

      case '404':
        script.error("""
          ❌ GitHub App is NOT installed on '${repo}'
             → Go to: https://github.com/${repo}
             → Settings → Integrations → GitHub Apps → install your app
        """)
        break

      case '401':
        script.error("❌ Token unauthorized checking installation — token may be scoped to wrong org")
        break

      default:
        script.error("❌ Unexpected response checking repo installation — HTTP ${httpCode}\\n${body}")
    }
  }

  // ─────────────────────────────────────────────────────────────
  // PRIVATE — generate repo-scoped installation token via API
  // ─────────────────────────────────────────────────────────────
  private String _createRepoToken(String jwt) {
    def repo = script.env.GH_REPO
    def installationId = script.env.GH_APP_INSTALLATION_ID

    if (!installationId) {
      script.error("❌ GH_APP_INSTALLATION_ID not set — cannot generate repo token")
    }

    def repoName = repo.split('/')[-1]

    script.echo "   Generating repo-scoped installation token for '${repoName}'..."

    def bodyJson = new groovy.json.JsonBuilder([repositories: [repoName]]).toString()

    def response = script.sh(
      script: """
        curl -s -w "\\n%{http_code}" -X POST \\
          -H "Authorization: Bearer ${jwt}" \\
          -H "Accept: application/vnd.github+json" \\
          -d '${bodyJson}' \\
          ${GITHUB_API}/app/installations/${installationId}/access_tokens
      """,
      returnStdout: true
    ).trim()

    def lines    = response.split('\n')
    def httpCode = lines[-1]
    def body     = lines[0..-2].join('\n')

    if (httpCode != '201') {
      script.error("❌ Failed to generate repo token — HTTP ${httpCode}\\n${body}")
    }

    def jsonStr = new JsonSlurper().parseText(body)
    script.echo "   ✅ Repo token generated successfully (expires at ${jsonStr.expires_at})"
    return jsonStr.token
  }
}